spring:
  application:
    name: qk-management

  # 数据库连接信息
  datasource:
    url: jdbc:mysql://localhost:3306/web
    username: root
    password: 88888888
    driver-class-name: com.mysql.cj.jdbc.Driver


  servlet:
    multipart:
      # 文件上传大小限制
      max-file-size: 10MB
      # 请求大小限制
      max-request-size: 10MB


# mybatis 配置
#mybatis:
#  mapper-locations: classpath:mapper/*.xml # Mapper XML 文件位置
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出 SQL 日志
#    map-underscore-to-camel-case: true # 驼峰命名转换

# mybatis-plus 配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # 输出 SQL 日志
    map-underscore-to-camel-case: true # 驼峰命名转换
  mapper-locations: mapper/*.xml # Mapper XML 文件位置
  global-config:
    db-config:
      id-type: auto # 主键自增

#阿里云OSS
aliyun:
  oss:
    endpoint: https://oss-cn-beijing.aliyuncs.com
    bucketName: codermey-qk-management
    region: cn-beijing